name: Update GScholar Citations Bar
on:
  schedule:
   - cron: '0 08 */1 * *'
  workflow_dispatch:

jobs:
  updateImage:
    name: Update profile image with newer citations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install numpy seaborn matplotlib playwright asyncio
          playwright install
          python ggscholar_graph.py --out "barplot"
          
      # Update Image ReadME
      - name: Update Image - README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add barplot.png
          git diff-index --quiet HEAD || (git commit -a -m "Update Chart" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

