name: Update GScholar Citations Bar
on:
  schedule:
    - cron: "0 08 */1 * *"
  workflow_dispatch:

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  updateImage:
    name: Update profile image with newer citations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Astral's UV
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.14"

      - name: Get Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          uv pip install --upgrade pip
          uv pip install numpy seaborn matplotlib playwright asyncio rich
          playwright install
          python ggscholar_graph.py --out "${{ github.workspace }}/components/data/"

      # Update Image ReadME
      - name: Update Image - README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ github.workspace }}/components/data/barplot.png ${{ github.workspace }}/components/data/citations.json
          git diff-index --quiet HEAD || (git commit -a -m "Update Chart & Data" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
