name: Update GScholar Citations Bar
on:
  workflow_dispatch:

jobs:
  updateImage:
    name: Update profile image with newer citations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install numpy seaborn beautifulsoup4 matplotlib requests
          python python ggscholar_graph.py --out "barplot" 
      
      - name: Generate image
        run: echo Hello, world!
          
      # Update Image ReadME
      - name: Update Image - README

