name: Update GScholar Citations Bar & Data
on:
  schedule:
    - cron: "0 08 * * 1"
  workflow_dispatch:

jobs:
  updateImage:
    name: Update profile image with newer citations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Get Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "scrapper/.python-version"

      - name: Install Astral's UV
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.2"

      - name: Install Dependencies & Run Script
        run: |
          cd scrapper
          uv sync --locked
          uv run playwright install chromium
          uv run python ggscholar_graph.py --out "${{ github.workspace }}/portfolio/public/"

      # Update Image ReadME
      - name: Update Image - README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ github.workspace }}/portfolio/public/barplot.png ${{ github.workspace }}/portfolio/public/citations.json
          git diff-index --quiet HEAD || (git commit -a -m "Update Chart & Data" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
